[package]
name = "nexus-serialize"
version = "0.1.0"
edition = "2021"
authors.workspace = true
description.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
