[package]
name = "nexus-observer"
version = "0.1.0"
edition = "2021"
authors.workspace = true
description.workspace = true

[dependencies]
actix = { workspace = true }
nexus-hashmap = { path = "../nexus-hashmap" }
nexus-counters = { path = "../nexus-counters" }
