[package]
name = "nexus-core"
version = "0.1.0"
edition = "2021"
authors.workspace = true
description.workspace = true

[dependencies]
actix = { workspace = true }
serde = { worspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true }
