[package]
name = "nexus-session-store"
version = "0.1.0"
edition = "2021"
authors.workspace = true
description.workspace = true

[dependencies]
nexus-ids = { path = "../nexus-ids" }
nexus-hashmap = { path = "../nexus-hashmap" }
